### ISSUE TITLE
Edge case in `num-range` tag: TypeError: Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by thegoatherder** [spencermountain/compromise#876]
Compromise is throwing an uncaught exception for what I imagine is an extreme edge case of input text containing the `num-range` tag. The input text itself appears to be a typo in some medical text.

`10.-200 ug/L`

I imagine the author meant to write:

`10-200 ug/L` (which throws no error)

## Steps to Reproduce

Execute the following code:

```js
const nlp = require('compromise')
let text  = '10.-200 ug/L'
let doc = nlp(text)  //<-- exception thrown here
```

## Actual Behaviour: Exception Thrown

```text
c:\myproject\node_modules\compromise\builds\compromise.js:10418
      terms[2].tag('Cardinal', 'num-range', doc.world);
               ^

TypeError: Cannot read property 'tag' of undefined
    at createPhrase (c:\myproject\node_modules\compromise\builds\compromise.js:10418:16)
    at c:\myproject\node_modules\compromise\builds\compromise.js:10457:27
    at Array.forEach (<anonymous>)
    at contractions$1 (c:\myproject\node_modules\compromise\builds\compromise.js:10443:14)
    at tagger$1 (c:\myproject\node_modules\compromise\builds\compromise.js:12670:11)
    at Doc$1.tagger (c:\myproject\node_modules\compromise\builds\compromise.js:14473:14)
    at nlp (c:\myproject\node_modules\compromise\builds\compromise.js:14556:11)
    at Object.<anonymous> (c:\myproject\scratch.js:69:11)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

## Error Line

```js
if (isOrdinal.test(term.text)) {
      terms[0].tag('Ordinal', 'ord-range', doc.world);
      terms[2].tag('Ordinal', 'ord-range', doc.world);
    } else if (isNumber.test(term.text)) {
      terms[0].tag('Cardinal', 'num-range', doc.world);
      terms[2].tag('Cardinal', 'num-range', doc.world);   // <---- EXCEPTION THROWN HERE
    } else if (isTime.test(term.text)) {
      terms[0].tag('Time', 'time-range', doc.world);
      terms[1].tag('Date', 'time-range', doc.world);
      terms[2].tag('Time', 'time-range', doc.world);
    } //make these terms implicit
```

The `terms` array has a length of `1`, but compromise is expecting a length of `3`:

![image](https://user-images.githubusercontent.com/389668/134000614-624e7445-271b-405d-84ea-b9a46890029e.png)

## Expected Behaviour

I think probably that `compromise` should test `terms.length > 0` - if this results in `false` then the `num-range` tag should be abandoned. What do you think @spencermountain ?

**Comment by thegoatherder** [comment]
Thanks a million Spence for the quick fix!

> --

-----------------------------------------------------------
"Are you sleep walking through your waking life
      ...or wake walking through your dreams?"

**Comment by spencermountain** [comment]
np. released as 13.11.4
