### ISSUE TITLE
Error: While trying to resolve module `grad-school`

### ISSUE THREAD

**Issue by iamrohitagg** [spencermountain/compromise#928]
I am trying to use this package in my react-native project but I am getting the following error:
```
error: Error: While trying to resolve module `grad-school` from file `/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/compromise/src/1-one/tag/methods/addTags/index.js`, the package `/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/grad-school/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/grad-school/builds/grad-school.cjs`. Indeed, none of these files exist:

  * /Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/grad-school/builds/grad-school.cjs(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
  * /Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/grad-school/builds/grad-school.cjs/index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
    at DependencyGraph.resolveDependency (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/node-haste/DependencyGraph.js:243:17)
    at Object.resolve (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/Users/classicinformatics/Desktop/stewart-mobile-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 3)
```
The error comes from me after importing the package
```
const nlp = require('compromise')
```

**Comment by spencermountain** [comment]
hi Rohit, weird! I've never seen that one. I don't know anything about react-native, so I may need some help.
if you visit `/node_modules/grad-school/builds/` the files aren't there? did you install with npm?
i just tried a fresh install and they are there.
cheers

**Comment by iamrohitagg** [comment]
Hi Spencer. Thanks for your fast reply!
I have checked `node_modules/grad-school/builds/` and all the files are there for me. But I am still getting the error.

**Comment by iamrohitagg** [comment]
I had to downgrade to version `"^13.11.4"` to get this working.

**Comment by spencermountain** [comment]
hey Rohit, do you wanna see if this works now, in 14.3.0?
sometimes these esmodule issues are just config whackamole
cheers

**Comment by iamrohitagg** [comment]
Hey Spencer, it's working now for version 14.3.0
