### ISSUE TITLE
How can I find the tense form of a sentence?

### ISSUE THREAD

**Issue by Samar-080301** [spencermountain/compromise#963]
If I have a sentence like "I am a boy". Which function should I use to find its tense form?

**Comment by spencermountain** [comment]
hey @Samar-080301 - this is a good question. I would do this:
```js
let doc = nlp("I am a boy")
console.log(doc.verbs().json().map(obj => obj.verb.grammar))
// [ { form: 'simple-present', tense: 'PresentTense', copula: true } ]
```

this will loop over every verb in a sentence, which is not perfect.
`"he said i am a boy"` would produce:
```js
[
  { form: 'simple-past', tense: 'PastTense', copula: false },
  { form: 'simple-present', tense: 'PresentTense', copula: true }
]
```

right now you'll have to decide which verb is the 'main' one, for a sentence. We used to offer that, but it got a little sloppy.

I'd love to parse sentence grammar better, it can get pretty tricky. You may want to remove conditional clauses and things, if your sentences are complex.
cheers

**Comment by Samar-080301** [comment]
I wrote this code.
```
import nlp from 'compromise'
let doc = nlp("I am a boy")
console.log(doc.verbs().json())
```

But it returned an error as.
```
import nlp from 'compromise'
           ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by Samar-080301** [comment]
And this code.
```

let doc = nlp("I am a boy")
console.log(doc.verbs().json())
```

Also returned an error as.
```
/home/samar/node_modules/compromise/src/three.js:1
import nlp from './two.js'
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/samar/Desktop/twitter_tense/main.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by spencermountain** [comment]
looks like you'll need `const nlp = require('compromise')` instead of the import line.
make sure you also run `npm install compromise`
cheers

**Comment by spencermountain** [comment]
this has been added in 14.6.0
```js
let doc = nlp("I am a boy")
console.log(doc.sentences().json()[0].sentence)
/*
{
  subject: 'i',
  verb: 'am',
  predicate: 'a boy',
  grammar: { tense: 'PresentTense' }
}
*/
```
cheers

**Comment by Samar-080301** [comment]
Thanks for your help sir!
