### ISSUE TITLE
uncaughtException: Cannot find module 'compromise/one'

### ISSUE THREAD

**Issue by AkshayDudhe** [spencermountain/compromise#979]
I am using compromise in NodeJS 

I imported the package with:
```
const nlp = require('compromise/one')
```

When I execute code it gives this error:

```
uncaughtException: Cannot find module 'compromise/one'\nError: Cannot find module 'compromise/one'\n 
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/usr/src/app/services/textAnalysisService.js:21:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad 
(internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)","meta":{"date":"Wed Nov 09 2022 10:22:02 GMT+0000 (Coordinated Universal Time)","err":{"code":"MODULE_NOT_FOUND","message":"Cannot find module 'compromise/one'","stack":"Error: Cannot find module 'compromise/one'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/usr/src/app/services/textAnalysisService.js:21:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"},"error":{"code":"MODULE_NOT_FOUND"},"exception":true,"os":{"loadavg":[4.986328125,3.8779296875,3.42529296875],"uptime":24190},"process":{"argv":["/usr/local/bin/node","/usr/src/app/index.js"],"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"external":172742,"heapTotal":39677952,"heapUsed":26087408,"rss":70053888},"pid":100,"uid":0,"version":"v10.15.0"},"stack":"Error: Cannot find module 'compromise/one'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n 
   at Object.<anonymous> (/usr/src/app/services/textAnalysisService.js:21:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)","trace":[{"column":15,"file":"internal/modules/cjs/loader.js","function":"Module._resolveFilename","line":581,"method":"_resolveFilename","native":false},{"column":25,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":507,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":637,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":22,"method":null,"native":false},{"column":13,"file":"/usr/src/app/services/textAnalysisService.js","function":null,"line":21,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false
```

Evnironment:
NodeJS: v12
Compromise: 14.7.0

**Comment by AkshayDudhe** [comment]
@spencermountain thanks for reply!
I used your syntax but I am getting same error. When I used older version 13.7.4 and used syntax  your syntax it was working. Do you have any idea why this is not working for latest version?

I also observed that tokenizer at 'compromise' is bit slower than 'compromise/one'. This will cause performance issue for me. Is there any way I can use the tokenizer at 'compromise/one' or reduce time taken by 'compromise' tokenizer.

**Comment by spencermountain** [comment]
hey ashkay, yep [v14](https://github.com/spencermountain/compromise/releases/tag/14.0.0) moved to es-modules, but provides commonjs builds as well. Most existing setups should work, but it depends on your build system.

yep, compromise by default loads compromise/three. compromise/one is much faster - it does only tokenization. compromise/two is slower because it does tagging, and additional analysis. Depending on your use case, you may only need compromise/one.

cheers
